version: '3.7'

networks:
  main:

services:

  nginx:
    image: nginx:1.17.10
    container_name: nginx
    depends_on:
      - products-service
      - extracts-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      main:
        aliases:
          - nginx

  products-service:
    container_name: products-service
    build:
      context: ./products-api
      dockerfile: Dockerfile
    volumes:
      - ./products-api:/usr/app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      APP_ENV: dev
      PORT: 3000
      DATABASE_URL: "postgresql://postgres:postgres@net_postgres:5432/net_store?schema=public"
      REDIS_PORT: 6379
    depends_on:
      - net_postgres
    links:
      - net_postgres:database
      - net_redis:redis
    command: bash -c "yarn && yarn dev"
    restart: on-failure
    networks:
      main:
        aliases:
          - products-service

  extracts-service:
    container_name: extracts-service
    build:
      context: ./extracts-api/
      dockerfile: Dockerfile
    volumes:
      - ./extracts-api:/usr/app
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      APP_ENV: dev
      PORT: 3001
      DB_HOST: net_postgres
      DB_PORT: 5432
      DB_NAME: net_store
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_PORT: 6379
    depends_on:
      - net_postgres
    links:
      - net_postgres:database
      - net_redis:redis
    command: bash -c "yarn && yarn dev"
    restart: on-failure
    networks:
      main:
        aliases:
          - extracts-service

  postgres:
    container_name: net_postgres
    image: postgres:11.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: net_store
    restart: always
    networks:
      main:
        aliases:
          - net_postgres

  redis:
    container_name: net_redis
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - './.data/redis:/data'
    networks:
      main:
        aliases:
          - net_redis
    restart: always

  # rabbitmq:
  #   container_name: net_rabbitmq
  #   ports:
  #     - '15672:15672'
  #     - '5672:5672'
  #   image: registry.dotgroup.com.br/dot/centos7-rabbitmq37
  #   command: /opt/app-root/services.sh
  #   environment:
  #     VIRTUAL_HOST: 'rabbitmq'
  #   networks:
  #     main:
  #       aliases:
  #         - rabbitmq


